import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/styles/globals.css";
import "@/styles/article.css";

import { headers } from "next/headers";
import Link from "next/link";
import LangLink from "@/components/LangLink";
import HtmlLangSetter from "@/components/HtmlLangSetter";
import HeaderTopMenu from "@/components/HeaderTopMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const pathname = headersList.get("x-pathname") || "";

  const getLang = (path: string): string => {
    if (path.startsWith("/fr")) return "fr";
    return "en";
  };

  const lang = getLang(pathname);

  return (
    <html lang={lang}>
      <head>
        <meta name="locale" content={lang} />
        <meta name="twitter:site" content="@reblogdemo" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-gradient-to-b from-white to-gray-50 dark:from-gray-900 dark:to-gray-950`}
      >
        <HtmlLangSetter />

        <header className="py-6">
          <div className="max-w-6xl mx-auto px-6">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between space-y-4 sm:space-y-0">
              <Link
                href="/"
                className="text-2xl font-bold text-blue-600 dark:text-blue-400 tracking-tight"
              >
                Reblog Demo
              </Link>
              <HeaderTopMenu lang={lang} />
            </div>
          </div>
        </header>

        <main className="flex-1 max-w-6xl w-full mx-auto px-6">
          {children}
        </main>

        <footer className="py-12 bg-gray-50 dark:bg-gray-900">
          <div className="max-w-6xl mx-auto px-6">
            <div className="flex flex-col md:flex-row justify-between items-center space-y-6 md:space-y-0">
              <div className="flex items-center space-x-4">
                <span className="text-blue-600 dark:text-blue-400 font-bold text-xl">Reblog Demo</span>
                <span className="text-gray-400 dark:text-gray-500">|</span>
                <span className="text-sm text-gray-500 dark:text-gray-400">Explore. Learn. Create.</span>
                <span className="text-gray-400 dark:text-gray-500">|</span>
                <div className="flex space-x-2">
                  <LangLink href="/" label="EN" lang="en" />
                  <LangLink href="/fr" label="FR" lang="fr" />
                </div>
              </div>
              <div className="text-sm text-gray-500 dark:text-gray-400">
                © {new Date().getFullYear()} Reblog.
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
